Web3Lab/Models/Answer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web3Lab.Models
{
    public class Answer
    {
        public List<Quiz> answers = new List<Quiz>();
        public int correctAnswer = 0;

        private static Answer instance = null;

        public static Answer Instance
        {
            get
            {
                if (instance == null)
                    instance = new Answer();

                return instance;
            }
        }


        public void Add(Quiz quiz)
        {
            if (quiz.CheckAnswer())
                correctAnswer++;

            answers.Add(quiz);
        }
    }
}

Web3Lab/Models/ErrorViewModel.cs
using System;

namespace Web3Lab.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Web3Lab/Models/Quiz.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web3Lab.Models
{
    public class Quiz
    {
        public double firstValue { get; set; }
        public double secondValue { get; set; }
        public double answer { get; set; }
        public string operand { get; set; }

        public Quiz()
        {

            Random rnd = new Random();

            firstValue = rnd.Next(20);
            secondValue = rnd.Next(20);

            string[] operands = { "+", "-", "*", "/" };
            operand = operands[rnd.Next(4)];
        }


        public bool CheckAnswer()
        {
            double correctAnswer = default;
            switch (operand)
            {
                case "+":
                    correctAnswer = firstValue + secondValue;
                    break;
                case "-":
                    correctAnswer = firstValue - secondValue;
                    break;
                case "*":
                    correctAnswer = firstValue * secondValue;
                    break;
                case "/":
                    correctAnswer = firstValue / secondValue;
                    break;
            }

            return correctAnswer == answer ? true : false;
        }
    }
}

Web3Lab/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Web3Lab.Models;

namespace Web3Lab.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Web3Lab/Controllers/QuizController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Web3Lab.Models;

namespace Web3Lab.Controllers
{
    public class QuizController : Controller
    {
        [HttpGet]
        public IActionResult Quiz()
        {
            return View(new Quiz());
        }

        [HttpPost]
        public IActionResult Quiz(Quiz operation, string action)
        {
            if (ModelState.IsValid)
            {
                if (operation.CheckAnswer())
                    Answer.Instance.correctAnswer++;

                Answer.Instance.answers.Add(operation);
                //Answers.Instance.Add(operation);
            }
            else
            {
                ModelState.AddModelError("YourAnswer", "недопустимый формат ответа");
                return View(operation);
            }

            if (action == "Next")
                return View(new Quiz());

            return RedirectToAction("QuizResult");

        }

        public IActionResult QuizResult()
        {
            return View(Answer.Instance);
        }
    }
}

Web3Lab/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-left">
    <h1 class="display-4">Menu</h1>
</div>
<ul>
    <li><a asp-area="" asp-controller="Quiz" asp-action="Quiz">Quiz</a></li>
    <li><a asp-area="" asp-controller="Quiz" asp-action="QuizResult">QuizResult</a></li>
</ul>

Web3Lab/Views/Quiz/Quiz.cshtml

@{
    ViewData["Title"] = "Quiz";
}

<h1>Quiz</h1>

@model Web3Lab.Models.Quiz
<div class="CalcMenu">
    <h2>@Model.firstValue  @Model.operand @Model.secondValue = ?</h2>
    <form asp-antiforgery="true" asp-action="Quiz" asp-controller="Quiz" method="post">
        <div class="validation" asp-validation-summary="ModelOnly"></div>
        <input name="answer" type="text">  <span asp-validation-for="answer"></span>
        <br>
        <input type="submit" value="Next" name="Action">
        <input type="submit" value="Finish" name="Action">
        <input style="display:none" name="firstValue" value="@Model.firstValue">
        <input style="display:none" name="operand" value="@Model.operand">
        <input style="display:none" name="secondValue" value="@Model.secondValue">
    </form>
</div>

Web3Lab/Views/Quiz/QuizResult.cshtml

@{
    ViewData["Title"] = "QuizResult";
}

<h1>QuizResult</h1>
@model Web3Lab.Models.Answer

<div class="CalcMenu">
    <h1>Right Answers @Model.correctAnswer out @Model.answers.Count </h1>
    <ul>
        @foreach (var p in Model.answers)
        {
            <li>@p.firstValue @p.operand @p.secondValue = @p.answer</li>
        }
    </ul>
</div>

Web3Lab/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web3Lab</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Web3Lab</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Web3Lab - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>